"""Distributed sampling helpers for faithful DriveVLA Stage-2 reproduction.

The public checkpoint was produced at 174,312 optimizer steps after 27 epochs.
With 103,288 NAVSIM training scenes this identifies a 6,456-step epoch and a
global batch of 16.  The paper reports 16 GPUs, so the reference layout is
16 ranks with one sample per rank.

Using 8 ranks with two samples per rank is mathematically the same global
batch only when padding is applied *after* shuffling, as PyTorch's reference
``DistributedSampler`` does.  Padding the dataset before ``randperm`` changes
the complete permutation and therefore the entire optimization trajectory.
"""

from __future__ import annotations

import math
from typing import Iterator

import torch
from torch.utils.data import Dataset
from torch.utils.data.distributed import DistributedSampler


class ReferenceGlobalBatchDistributedSampler(DistributedSampler):
    """Replay reference global batches on a different rank/batch layout.

    For example, reference ``16 ranks x batch 1`` can be reproduced with
    ``8 ranks x batch 2`` or ``4 ranks x batch 4``.  Every optimizer step sees
    the same global-batch members generated by the reference sampler.  Their
    rank-local order can differ. This is immaterial for a deterministic
    per-sample network, but it prevents bitwise replay here because the action
    head has dropout even when the frozen backbone is held in eval mode. It can
    also change frozen-backbone stochastic depth and LoRA dropout when that
    backbone follows train-mode semantics.
    """

    def __init__(
        self,
        dataset: Dataset,
        *,
        num_replicas: int,
        rank: int,
        per_rank_batch_size: int,
        gradient_accumulation_steps: int = 1,
        reference_global_batch_size: int = 16,
        shuffle: bool = True,
        seed: int = 0,
    ) -> None:
        if num_replicas <= 0:
            raise ValueError("num_replicas must be positive")
        if not 0 <= rank < num_replicas:
            raise ValueError(f"rank {rank} outside [0, {num_replicas})")
        if per_rank_batch_size <= 0:
            raise ValueError("per_rank_batch_size must be positive")
        if gradient_accumulation_steps <= 0:
            raise ValueError("gradient_accumulation_steps must be positive")
        effective_global_batch_size = (
            num_replicas * per_rank_batch_size * gradient_accumulation_steps
        )
        if effective_global_batch_size != reference_global_batch_size:
            raise ValueError(
                "Current effective global batch must equal the reference "
                "global batch: "
                f"{num_replicas} x {per_rank_batch_size} x "
                f"{gradient_accumulation_steps} != "
                f"{reference_global_batch_size}"
            )

        # Initialize standard attributes (epoch, seed, rank, shuffle) used by
        # Lightning and by DistributedSampler.set_epoch().  Its num_samples is
        # intentionally replaced below because our unit is a global batch.
        super().__init__(
            dataset,
            num_replicas=num_replicas,
            rank=rank,
            shuffle=shuffle,
            seed=seed,
            drop_last=False,
        )
        self.per_rank_batch_size = int(per_rank_batch_size)
        self.gradient_accumulation_steps = int(gradient_accumulation_steps)
        self.reference_global_batch_size = int(reference_global_batch_size)
        self.num_global_batches = int(
            math.ceil(len(dataset) / self.reference_global_batch_size)
        )
        self.total_size = self.num_global_batches * self.reference_global_batch_size
        self.num_samples = (
            self.num_global_batches
            * self.per_rank_batch_size
            * self.gradient_accumulation_steps
        )

    def _reference_indices(self) -> torch.Tensor:
        if self.shuffle:
            generator = torch.Generator()
            generator.manual_seed(self.seed + self.epoch)
            indices = torch.randperm(len(self.dataset), generator=generator)
        else:
            indices = torch.arange(len(self.dataset), dtype=torch.int64)

        padding_size = self.total_size - len(indices)
        if padding_size:
            if padding_size <= len(indices):
                indices = torch.cat((indices, indices[:padding_size]))
            else:
                repeats = math.ceil(padding_size / len(indices))
                indices = torch.cat(
                    (indices, indices.repeat(repeats)[:padding_size])
                )
        if len(indices) != self.total_size:
            raise RuntimeError(
                f"Sampler padded to {len(indices)}, expected {self.total_size}"
            )
        return indices

    def __iter__(self) -> Iterator[int]:
        global_batches = self._reference_indices().view(
            self.num_global_batches, self.reference_global_batch_size
        )
        local_samples_per_optimizer_step = (
            self.per_rank_batch_size * self.gradient_accumulation_steps
        )
        columns = self.rank + torch.arange(
            local_samples_per_optimizer_step
        ) * self.num_replicas
        local_indices = global_batches[:, columns].reshape(-1)
        if len(local_indices) != self.num_samples:
            raise RuntimeError(
                f"Rank received {len(local_indices)} samples, expected {self.num_samples}"
            )
        return iter(local_indices.tolist())

    def __len__(self) -> int:
        return self.num_samples
