#!/usr/bin/env bash
# =============================================================================
# DriveDreamer-Policy — User Environment Configuration
# Copy this file and fill in the paths for your own setup.
# Then source it before running any of the numbered pipeline scripts:
#   source env.sh
# =============================================================================

# Resolve paths relative to this repository even when sourced elsewhere.
export DRIVEDREAMER_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# Optional machine-local paths. Entries should use the ``${VAR:-value}``
# pattern so explicit one-shot DLC environment variables retain precedence.
if [[ "${VLA_DRIVE_SKIP_ENV_LOCAL:-0}" != "1" && -f "$DRIVEDREAMER_ROOT/env.local.sh" ]]; then
  source "$DRIVEDREAMER_ROOT/env.local.sh"
fi
# Optional shared-data checkout/root.  Machine-specific CPFS mounts belong in
# env.local.sh; the portable fallback is always this active checkout.
export DRIVEDREAMER_SHARED_ROOT="${DRIVEDREAMER_SHARED_ROOT:-$DRIVEDREAMER_ROOT}"

# ── PPU CUDA-compatible runtime ───────────────────────────────────────────────
# The local PPU SDK exposes a CUDA-compatible PyTorch device/runtime.
# Keep the preinstalled PPU torch/triton builds; do not replace them with
# upstream NVIDIA wheels.
export CUDA_HOME="${CUDA_HOME:-/usr/local/cuda-12.4}"
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH="$CUDA_HOME/lib64:${LD_LIBRARY_PATH:-}"

# ── HuggingFace / Torch cache ─────────────────────────────────────────────────
export SHARED_WEIGHT_ROOT="${SHARED_WEIGHT_ROOT:-$DRIVEDREAMER_ROOT/weights}"
export HF_HOME="${HF_HOME:-$SHARED_WEIGHT_ROOT/.cache/huggingface}"
export TORCH_HOME="${TORCH_HOME:-$DRIVEDREAMER_ROOT/.cache/torch}"
export MPLCONFIGDIR="${MPLCONFIGDIR:-$DRIVEDREAMER_ROOT/.cache/matplotlib}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$DRIVEDREAMER_ROOT/.cache}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-$DRIVEDREAMER_ROOT/.cache/triton}"
export NO_ALBUMENTATIONS_UPDATE="${NO_ALBUMENTATIONS_UPDATE:-1}"
# Uncomment if you use a mirror (e.g. in mainland China):
# export HF_ENDPOINT=https://hf-mirror.com

# ── NAVSIM / nuPlan paths ─────────────────────────────────────────────────────
export NUPLAN_MAP_VERSION="${NUPLAN_MAP_VERSION:-nuplan-maps-v1.0}"
export NAVSIM_PUBLIC_ROOT="${NAVSIM_PUBLIC_ROOT:-${OPENSCENE_DATA_ROOT:-$DRIVEDREAMER_ROOT/navsim_dataset_raw}}"
export NAVSIM_TRAINVAL_SENSOR_ROOT="${NAVSIM_TRAINVAL_SENSOR_ROOT:-$NAVSIM_PUBLIC_ROOT/trainval_all/trainval_sensor_blobs/trainval}"
# Frozen-feature cache generated by pre_cache.sh.  The project workspace is a
# shared mount in the formal container, so keep the multi-TiB cache in its own
# repository-level directory. Compiler/Triton caches remain node-local and are
# configured by the launchers separately.
export NAVSIM_FEATURE_CACHE_ROOT="${NAVSIM_FEATURE_CACHE_ROOT:-$DRIVEDREAMER_SHARED_ROOT/navsim_feature_cache/navsim_v1_qwen3vl2b_wan21_ppd_v1}"
# Qwen visual features account for about 2.7 TiB (roughly 90% of feature I/O).
# On 16 PPU the shared-storage reads cost far more than recomputing the frozen
# Qwen vision tower, while Wan+PPD are only about 303 GiB and remain profitable
# to cache. Full qwen,wan,ppd remains available as an explicit override.
export NAVSIM_CACHE_COMPONENTS="${NAVSIM_CACHE_COMPONENTS:-wan,ppd}"
export NAVSIM_CACHE_STRICT="${NAVSIM_CACHE_STRICT:-1}"
export NAVSIM_USE_FEATURE_CACHE="${NAVSIM_USE_FEATURE_CACHE:-1}"
export NAVSIM_RAM_CACHE_COMPONENTS="${NAVSIM_RAM_CACHE_COMPONENTS:-wan,ppd}"
export NAVSIM_RAM_CACHE_ROOT="${NAVSIM_RAM_CACHE_ROOT:-/dev/shm/drivedreamer-navsim-cache}"
export NAVSIM_RAM_RESERVE_GB="${NAVSIM_RAM_RESERVE_GB:-400}"
export NAVSIM_RAM_COPY_WORKERS="${NAVSIM_RAM_COPY_WORKERS:-8}"
export NAVSIM_RAM_DATA_ROOT="${NAVSIM_RAM_DATA_ROOT:-/dev/shm/drivedreamer-navsim-data}"
export NAVSIM_METADATA_COPY_WORKERS="${NAVSIM_METADATA_COPY_WORKERS:-16}"
export NUPLAN_MAPS_ROOT="${NUPLAN_MAPS_ROOT:-$DRIVEDREAMER_ROOT/navsim_dataset_raw/maps}"
export NAVSIM_EXP_ROOT="${NAVSIM_EXP_ROOT:-$DRIVEDREAMER_ROOT/navsim_exp}"
export NAVSIM_DEVKIT_ROOT="${NAVSIM_DEVKIT_ROOT:-$DRIVEDREAMER_ROOT/navsim}"
export OPENSCENE_DATA_ROOT="${OPENSCENE_DATA_ROOT:-$DRIVEDREAMER_ROOT/navsim_dataset_raw}"
export DATA_ROOT="${DATA_ROOT:-$DRIVEDREAMER_ROOT/navsim_dataset}"
export PYTHONPATH="$DRIVEDREAMER_ROOT:$DRIVEDREAMER_ROOT/navsim_data_process:$NAVSIM_DEVKIT_ROOT:${PYTHONPATH:-}"

# ── Base VLM checkpoint ───────────────────────────────────────────────────────
# Output of step 7 (7-add_token.sh): Qwen3-VL-2B-Instruct with extended world & action tokens
export SOURCE_VLM="${SOURCE_VLM:-$SHARED_WEIGHT_ROOT/Qwen/Qwen3-VL-2B-Instruct}"
export BASE_VLM="${BASE_VLM:-$DRIVEDREAMER_ROOT/weights/derived/Qwen3-VL-2B-WorldAction}"
export VLM_ATTN_IMPLEMENTATION="${VLM_ATTN_IMPLEMENTATION:-flash_attention_2}"
export VIDEO_MODEL="${VIDEO_MODEL:-$SHARED_WEIGHT_ROOT/alibaba-pai/Wan2.1-Fun-V1.1-1.3B-InP}"
export PPD_MODEL="${PPD_MODEL:-$SHARED_WEIGHT_ROOT/gangweix/Pixel-Perfect-Depth/ppd.pth}"
export DEPTH_ANYTHING_MODEL="${DEPTH_ANYTHING_MODEL:-$SHARED_WEIGHT_ROOT/depth-anything/Depth-Anything-V2-Large/depth_anything_v2_vitl.pth}"
export DA3_MODEL="${DA3_MODEL:-$SHARED_WEIGHT_ROOT/depth-anything/da3metric-large}"
export RELEASE_MODEL="${RELEASE_MODEL:-$DRIVEDREAMER_ROOT/weights/yangzhou99/DriveDreamer-Policy}"

# ── Weights & Biases (optional) ───────────────────────────────────────────────
export WANDB_API_KEY="${WANDB_API_KEY:-}"
export WANDB_ENTITY="${WANDB_ENTITY:-local}"
export WANDB_PROJECT="${WANDB_PROJECT:-drivedreamer-policy}"
export WANDB_MODE="${WANDB_MODE:-offline}"
export VLA_DRIVE_ENV_LOADED=1
