#!/usr/bin/env bash
# =============================================================================
# DriveDreamer-Policy — shared, portable environment defaults.
# Copy env.local.example.sh to env.local.sh for machine-specific paths. All
# top-level entrypoints load this file automatically through load_env.sh.
# =============================================================================

# Resolve the code checkout from this file, not from an inherited shell
# variable. This prevents one checkout/worktree from accidentally launching
# code from another developer's checkout.
_vla_repository_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
export DRIVEDREAMER_ROOT="${_vla_repository_root}"

# Optional per-user overrides. This file is ignored by git; use it for machine
# specific mounts and credentials while keeping env.sh as the shared default.
if [[ "${VLA_DRIVE_SKIP_ENV_LOCAL:-0}" != "1" && -f "$DRIVEDREAMER_ROOT/env.local.sh" ]]; then
  source "$DRIVEDREAMER_ROOT/env.local.sh"
fi
if [[ "${DRIVEDREAMER_ROOT}" != "${_vla_repository_root}" ]]; then
  echo "[env] ignoring DRIVEDREAMER_ROOT override; code root is ${_vla_repository_root}" >&2
  export DRIVEDREAMER_ROOT="${_vla_repository_root}"
fi
unset _vla_repository_root

# Durable shared storage may be configured per machine in env.local.sh. The
# portable fallback stays inside this checkout.
export DRIVEDREAMER_SHARED_ROOT="${DRIVEDREAMER_SHARED_ROOT:-$DRIVEDREAMER_ROOT}"

# ── PPU CUDA-compatible runtime ───────────────────────────────────────────────
# The local PPU SDK exposes a CUDA-compatible PyTorch device/runtime.
# Keep the preinstalled PPU torch/triton builds; do not replace them with
# upstream NVIDIA wheels.
export CUDA_HOME="${CUDA_HOME:-/usr/local/cuda-12.4}"
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH="$CUDA_HOME/lib64:${LD_LIBRARY_PATH:-}"

# ── HuggingFace / Torch cache ─────────────────────────────────────────────────
export SHARED_WEIGHT_ROOT="${SHARED_WEIGHT_ROOT:-$DRIVEDREAMER_ROOT/weights}"
export HF_HOME="${HF_HOME:-$SHARED_WEIGHT_ROOT/.cache/huggingface}"
export TORCH_HOME="${TORCH_HOME:-$DRIVEDREAMER_ROOT/.cache/torch}"
export MPLCONFIGDIR="${MPLCONFIGDIR:-$DRIVEDREAMER_ROOT/.cache/matplotlib}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$DRIVEDREAMER_ROOT/.cache}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-$DRIVEDREAMER_ROOT/.cache/triton}"
export NO_ALBUMENTATIONS_UPDATE="${NO_ALBUMENTATIONS_UPDATE:-1}"
# Uncomment if you use a mirror (e.g. in mainland China):
# export HF_ENDPOINT=https://hf-mirror.com

# ── NAVSIM / nuPlan paths ─────────────────────────────────────────────────────
export NUPLAN_MAP_VERSION="${NUPLAN_MAP_VERSION:-nuplan-maps-v1.0}"
export NAVSIM_PUBLIC_ROOT="${NAVSIM_PUBLIC_ROOT:-$DRIVEDREAMER_ROOT/navsim_dataset_raw}"
export NAVSIM_TRAINVAL_SENSOR_ROOT="${NAVSIM_TRAINVAL_SENSOR_ROOT:-$NAVSIM_PUBLIC_ROOT/sensor_blobs/trainval}"
export NAVSIM_TEST_LOG_ROOT="${NAVSIM_TEST_LOG_ROOT:-$NAVSIM_PUBLIC_ROOT/navsim_logs/test}"
export NAVSIM_TEST_SENSOR_ROOT="${NAVSIM_TEST_SENSOR_ROOT:-$NAVSIM_PUBLIC_ROOT/sensor_blobs/test}"
# Frozen-feature cache generated by pre_cache.sh.  The project workspace is a
# shared mount in the formal container, so keep the multi-TiB cache in its own
# repository-level directory. Compiler/Triton caches remain node-local and are
# configured by the launchers separately.
export NAVSIM_FEATURE_CACHE_ROOT="${NAVSIM_FEATURE_CACHE_ROOT:-$DRIVEDREAMER_SHARED_ROOT/navsim_feature_cache/navsim_v1_qwen3vl2b_wan21_ppd_v1}"
# Qwen visual features account for about 2.7 TiB (roughly 90% of feature I/O).
# On 16 PPU the shared-storage reads cost far more than recomputing the frozen
# Qwen vision tower, while Wan+PPD are only about 303 GiB and remain profitable
# to cache. Full qwen,wan,ppd remains available as an explicit override.
export NAVSIM_CACHE_COMPONENTS="${NAVSIM_CACHE_COMPONENTS:-wan,ppd}"
export NAVSIM_CACHE_STRICT="${NAVSIM_CACHE_STRICT:-1}"
export NAVSIM_USE_FEATURE_CACHE="${NAVSIM_USE_FEATURE_CACHE:-1}"
export NAVSIM_RAM_CACHE_COMPONENTS="${NAVSIM_RAM_CACHE_COMPONENTS:-wan,ppd}"
export NAVSIM_RAM_CACHE_ROOT="${NAVSIM_RAM_CACHE_ROOT:-/dev/shm/drivedreamer-navsim-cache}"
export NAVSIM_RAM_RESERVE_GB="${NAVSIM_RAM_RESERVE_GB:-400}"
export NAVSIM_RAM_COPY_WORKERS="${NAVSIM_RAM_COPY_WORKERS:-8}"
export NAVSIM_RAM_DATA_ROOT="${NAVSIM_RAM_DATA_ROOT:-/dev/shm/drivedreamer-navsim-data}"
export NAVSIM_METADATA_COPY_WORKERS="${NAVSIM_METADATA_COPY_WORKERS:-16}"
export NUPLAN_MAPS_ROOT="${NUPLAN_MAPS_ROOT:-$NAVSIM_PUBLIC_ROOT/maps}"
export NAVSIM_EXP_ROOT="${NAVSIM_EXP_ROOT:-$DRIVEDREAMER_ROOT/navsim_exp}"
export NAVSIM_EVAL_ROOT="${NAVSIM_EVAL_ROOT:-$NAVSIM_EXP_ROOT}"
export NAVSIM_DEVKIT_ROOT="${NAVSIM_DEVKIT_ROOT:-$DRIVEDREAMER_ROOT/navsim}"
export NAVSIM_V1_DEVKIT_ROOT="${NAVSIM_V1_DEVKIT_ROOT:-$DRIVEDREAMER_ROOT/navsim_v1.1/navsim}"
export OPENSCENE_DATA_ROOT="${OPENSCENE_DATA_ROOT:-$NAVSIM_PUBLIC_ROOT}"
export DATA_ROOT="${DATA_ROOT:-$DRIVEDREAMER_ROOT/navsim_dataset}"
export NAVSIM_DATALIST_PATH="${NAVSIM_DATALIST_PATH:-$DRIVEDREAMER_ROOT/train_meta.json}"
export NAVSIM_VIDEO_ROOT="${NAVSIM_VIDEO_ROOT:-$DATA_ROOT/navsim_video}"
export NAVSIM_V1_METRIC_CACHE_PATH="${NAVSIM_V1_METRIC_CACHE_PATH:-$DRIVEDREAMER_ROOT/navsim_exp/metric_cache_v1.1}"
export NAVSIM_V2_METRIC_CACHE_ROOT="${NAVSIM_V2_METRIC_CACHE_ROOT:-$DRIVEDREAMER_ROOT/navsim_exp}"
# Action-effect research artifacts are capability-scoped and never required by
# baseline training/inference. Personal shared mounts belong in env.local.sh.
export ACTION_EFFECT_CACHE_ROOT="${ACTION_EFFECT_CACHE_ROOT:-$DRIVEDREAMER_SHARED_ROOT/action_effect_cache}"
export ACTION_EFFECT_OUTPUT_ROOT="${ACTION_EFFECT_OUTPUT_ROOT:-$NAVSIM_EXP_ROOT/action_effect_world_model}"
# Frozen baseline used only by the opt-in action-effect feature-cache tool.
# The CLI can override both values without changing shared configuration.
export ACTION_EFFECT_BASELINE_RUN="${ACTION_EFFECT_BASELINE_RUN:-$NAVSIM_EXP_ROOT/qwen-visual-action-only-20260814_001706}"
export ACTION_EFFECT_BASELINE_STEP="${ACTION_EFFECT_BASELINE_STEP:-100000}"
export PYTHONPATH="$DRIVEDREAMER_ROOT:$DRIVEDREAMER_ROOT/navsim_data_process:$NAVSIM_DEVKIT_ROOT:${PYTHONPATH:-}"

# ── Base VLM checkpoint ───────────────────────────────────────────────────────
# Output of step 7 (7-add_token.sh): Qwen3-VL-2B-Instruct with extended world & action tokens
export SOURCE_VLM="${SOURCE_VLM:-$SHARED_WEIGHT_ROOT/Qwen/Qwen3-VL-2B-Instruct}"
export BASE_VLM="${BASE_VLM:-$DRIVEDREAMER_ROOT/weights/derived/Qwen3-VL-2B-WorldAction}"
export VLM_ATTN_IMPLEMENTATION="${VLM_ATTN_IMPLEMENTATION:-flash_attention_2}"
export VIDEO_MODEL="${VIDEO_MODEL:-$SHARED_WEIGHT_ROOT/alibaba-pai/Wan2.1-Fun-V1.1-1.3B-InP}"
export PPD_MODEL="${PPD_MODEL:-$SHARED_WEIGHT_ROOT/gangweix/Pixel-Perfect-Depth/ppd.pth}"
export DEPTH_ANYTHING_MODEL="${DEPTH_ANYTHING_MODEL:-$SHARED_WEIGHT_ROOT/depth-anything/Depth-Anything-V2-Large/depth_anything_v2_vitl.pth}"
export DA3_MODEL="${DA3_MODEL:-$SHARED_WEIGHT_ROOT/depth-anything/da3metric-large}"
export RELEASE_MODEL="${RELEASE_MODEL:-$DRIVEDREAMER_ROOT/navsim_exp/0808_11-agent-action-lr1e5-16g-bz_2-ga_1-train/final_model/pytorch_model.pt}"

# ── Optional VGGT-query teacher (feature/add-VGGT only) ──────────────────────
# VGGT is used only by the offline cache tool. Training and inference consume
# student query tokens and never import VGGT. Machine-local source/weight paths
# should be set in env.local.sh; empty defaults keep baseline workflows usable.
export VGGT_REPO="${VGGT_REPO:-}"
export VGGT_CHECKPOINT="${VGGT_CHECKPOINT:-}"
# Extend the existing world/action vocabulary by default, while keeping the
# output in a distinct directory. Override only if a different source is intended.
export VGGT_SOURCE_VLM="${VGGT_SOURCE_VLM:-$BASE_VLM}"
export VGGT_BASE_VLM="${VGGT_BASE_VLM:-$DRIVEDREAMER_ROOT/weights/derived/Qwen3-VL-2B-VGGTAction-V2-G15}"
export NAVSIM_VGGT_CACHE_ROOT="${NAVSIM_VGGT_CACHE_ROOT:-$DRIVEDREAMER_SHARED_ROOT/navsim_feature_cache/vggt_query_train_v2_layer11_global_m195}"
# V3 uses distinct artifacts so a V2 cache can never be accepted implicitly.
# The native codec is trained offline and is absent from student train/infer.
export VGGT_V3_CODEC_ROOT="${VGGT_V3_CODEC_ROOT:-$DRIVEDREAMER_SHARED_ROOT/navsim_feature_cache/vggt_native_codec_v3_l11_global}"
export VGGT_V3_CODEC="${VGGT_V3_CODEC:-$VGGT_V3_CODEC_ROOT/native_codec.pt}"
export NAVSIM_VGGT_V3_CACHE_ROOT="${NAVSIM_VGGT_V3_CACHE_ROOT:-$DRIVEDREAMER_SHARED_ROOT/navsim_feature_cache/vggt_query_train_v3_layer11_global_codec_m195}"
# Final-layer dense patch cache for the independent planning-conditioned
# bottleneck. It is read by train/inference; VGGT itself remains offline-only.
export NAVSIM_VGGT_DENSE_CACHE_ROOT="${NAVSIM_VGGT_DENSE_CACHE_ROOT:-$DRIVEDREAMER_SHARED_ROOT/navsim_feature_cache/vggt_dense_final_crop}"

# ── Weights & Biases (optional) ───────────────────────────────────────────────
export WANDB_API_KEY="${WANDB_API_KEY:-}"
export WANDB_ENTITY="${WANDB_ENTITY:-local}"
export WANDB_PROJECT="${WANDB_PROJECT:-drivedreamer-policy}"
export WANDB_MODE="${WANDB_MODE:-offline}"
export VLA_DRIVE_ENV_LOADED=1
