#!/usr/bin/env bash
set -euo pipefail

python -m tools.shared_future_candidate_consequence.build_balanced_split --mode smoke --split trainval --num-scenes 32 --output-dir reports/shared_future_candidate_consequence_gate_c
python -m tools.shared_future_candidate_consequence.build_controlled_candidates --split trainval --num-scenes 32 --num-candidates 16 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/smoke
python -m tools.shared_future_candidate_consequence.reproduce_gate_c0 --split trainval --num-scenes 32 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c
python -m tools.shared_future_candidate_consequence.build_gate_c_targets --split trainval --num-scenes 32 --actor-slots 16 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/smoke
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode smoke --num-scenes 32 --models linear,mlp --epochs 8 --batch-scenes 8 --device cpu --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/smoke
python -m tools.shared_future_candidate_consequence.build_balanced_split --mode full --split trainval --num-scenes 2000 --min-logs 40 --per-log-cap 50 --num-folds 5 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c
python -m tools.shared_future_candidate_consequence.build_controlled_candidates --split trainval --num-scenes 2000 --num-candidates 16 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/full
python -m tools.shared_future_candidate_consequence.build_balanced_split --mode all --split trainval --num-folds 5 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 1192 --shard-index 1191 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all_test
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 1192 --shard-index 1191 --seed 20260828 --force --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all_test
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 1192 --shard-index 961 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all_bench
python -m tools.shared_future_candidate_consequence.build_gate_c_targets --split trainval --num-scenes 2000 --actor-slots 16 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/full
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 9 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.export_episode_drive_candidates --mode asset-audit --split trainval --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 5 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 2 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 8 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 12 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 1 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 11 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 14 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 7 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 6 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 13 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 15 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.export_episode_drive_candidates --mode export --split trainval --scenes-per-log 1 --num-shards 1 --shard-index 0 --max-scenes 1 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/model_smoke
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 4 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 10 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 0 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 3 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_model_candidate_bank --mode shard --split trainval --num-candidates 16 --actor-slots 16 --num-shards 1 --shard-index 0 --max-scenes 1 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/model_smoke
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 17 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 19 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 27 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_model_candidate_bank --mode shard --split trainval --num-candidates 16 --actor-slots 16 --num-shards 1 --shard-index 0 --max-scenes 1 --force --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/model_smoke
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 22 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 16 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 20 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 28 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 26 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 25 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 21 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode smoke --groups O0 --folds 0 --models linear --epochs 1 --batch-scenes 128 --device cpu --job-name metric_vectorization_smoke --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/full
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 24 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 18 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 23 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 29 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 30 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 31 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.export_episode_drive_candidates --mode export --split trainval --scenes-per-log 2 --num-shards 4 --shard-index 2 --determinism-scenes 1 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.export_episode_drive_candidates --mode export --split trainval --scenes-per-log 2 --num-shards 4 --shard-index 0 --determinism-scenes 1 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.export_episode_drive_candidates --mode export --split trainval --scenes-per-log 2 --num-shards 4 --shard-index 1 --determinism-scenes 1 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.export_episode_drive_candidates --mode export --split trainval --scenes-per-log 2 --num-shards 4 --shard-index 3 --determinism-scenes 1 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.export_episode_drive_candidates --mode aggregate --split trainval --scenes-per-log 2 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_balanced_split --mode full --split trainval --num-scenes 45378 --min-logs 1192 --per-log-cap 50 --num-folds 5 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c
python -m tools.shared_future_candidate_consequence.export_episode_drive_candidates --mode aggregate --split trainval --scenes-per-log 2 --num-shards 4 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 34 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 33 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 32 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 40 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_model_candidate_bank --mode shard --split trainval --num-candidates 16 --actor-slots 16 --num-shards 8 --shard-index 0 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 35 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 36 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_model_candidate_bank --mode shard --split trainval --num-candidates 16 --actor-slots 16 --num-shards 8 --shard-index 4 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_model_candidate_bank --mode shard --split trainval --num-candidates 16 --actor-slots 16 --num-shards 8 --shard-index 5 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_model_candidate_bank --mode shard --split trainval --num-candidates 16 --actor-slots 16 --num-shards 8 --shard-index 1 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_model_candidate_bank --mode shard --split trainval --num-candidates 16 --actor-slots 16 --num-shards 8 --shard-index 3 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_model_candidate_bank --mode shard --split trainval --num-candidates 16 --actor-slots 16 --num-shards 8 --shard-index 2 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_model_candidate_bank --mode shard --split trainval --num-candidates 16 --actor-slots 16 --num-shards 8 --shard-index 7 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_model_candidate_bank --mode shard --split trainval --num-candidates 16 --actor-slots 16 --num-shards 8 --shard-index 6 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 38 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 39 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 42 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_model_candidate_bank --mode aggregate --split trainval --num-candidates 16 --actor-slots 16 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_model_oracle_store --num-candidates 16 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 43 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 37 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 44 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 41 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 48 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 49 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 46 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 50 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.analyze_model_candidate_diversity --num-candidates 16 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 48 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 49 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 50 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 51 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 47 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 46 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 52 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 45 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 53 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode pilot --groups O3,O8,O9 --models linear,mlp --epochs 8 --batch-scenes 256 --device cuda --seed 20260828 --job-name epoch8_calibration --store-dir outputs/shared_future_candidate_consequence_gate_c/full/oracle_store --job-root outputs/shared_future_candidate_consequence_gate_c/full/oracle_jobs --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/full
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 56 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode pilot --groups O3,O8,O9 --models linear,mlp --epochs 15 --batch-scenes 256 --device cuda --seed 20260828 --job-name epoch15_calibration --store-dir outputs/shared_future_candidate_consequence_gate_c/full/oracle_store --job-root outputs/shared_future_candidate_consequence_gate_c/full/oracle_jobs --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/full
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 55 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 57 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 54 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 58 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 59 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O3,O4,O5,O8,O9,O10,O11,O12,O13 --models linear,mlp --epochs 15 --batch-scenes 256 --device cuda --job-name model_oracle --store-dir outputs/shared_future_candidate_consequence_gate_c/all/model_candidate_oracle_store --job-root outputs/shared_future_candidate_consequence_gate_c/all/model_candidates/oracle_jobs --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.summarize_model_candidate_oracle --job-dir outputs/shared_future_candidate_consequence_gate_c/all/model_candidates/oracle_jobs/model_oracle --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 61 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.summarize_model_candidate_oracle --job-dir outputs/shared_future_candidate_consequence_gate_c/all/model_candidates/oracle_jobs/model_oracle --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 60 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 62 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 63 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 4 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 0 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 7 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 5 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 1 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 3 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 2 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 6 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 12 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 10 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 11 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 9 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 13 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 15 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 8 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 16 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 14 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 19 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 17 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 21 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 20 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 22 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 18 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 24 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 26 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 23 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 30 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 27 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 34 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 25 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 32 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 28 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 29 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 33 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 39 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 31 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 35 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 37 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 45 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 46 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 47 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 42 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 48 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 49 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 50 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 51 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 52 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 53 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 54 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 40 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 55 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 56 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 57 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 58 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 38 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 59 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 60 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 61 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 63 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 36 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 43 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 62 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 44 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_all_log_pipeline --split trainval --num-candidates 16 --actor-slots 16 --num-shards 64 --shard-index 41 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 3 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 7 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 0 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 1 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 6 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 2 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 4 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 5 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 8 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 10 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 11 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 9 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 13 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 12 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 15 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 14 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 16 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 17 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 18 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 19 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 21 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 20 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 22 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 23 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 24 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 26 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 25 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 27 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 29 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 28 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 30 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --split trainval --actor-slots 16 --num-shards 32 --shard-index 31 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.augment_current_actor_targets --mode aggregate --actor-slots 16 --num-shards 32 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.aggregate_all_log_pipeline --num-candidates 16 --actor-slots 16 --sample-targets 512 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.build_oracle_store --num-candidates 16 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.aggregate_all_log_pipeline --num-candidates 16 --actor-slots 16 --sample-targets 512 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O0 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O0 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O1 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O1 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O2 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O2 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O5 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O5 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O9 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O9 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O13 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O13 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O4 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O4 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O8 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O8 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O7 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O7 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.aggregate_all_log_pipeline --num-candidates 16 --actor-slots 16 --sample-targets 512 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O12 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O12 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O11 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O11 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O3 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O3 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all --heldout
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O6 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O6 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.run_oracle_decomposition --mode full --groups O10 --models linear,mlp --epochs 15 --batch-scenes 512 --device cuda --seed 20260828 --job-name formal_O10 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.aggregate_oracle_jobs --num-folds 5 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.summarize_model_candidate_oracle --job-dir outputs/shared_future_candidate_consequence_gate_c/all/model_candidates/oracle_jobs/model_oracle --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.finalize_gate_c_failure --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.visualize_gate_c --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m compileall -q tools/shared_future_candidate_consequence
bash -n tools/shared_future_candidate_consequence/*.sh
pytest -q tests
python -m tools.shared_future_candidate_consequence.visualize_gate_c --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.aggregate_oracle_jobs --num-folds 5 --seed 20260828 --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.finalize_gate_c_failure --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
python -m tools.shared_future_candidate_consequence.finalize_gate_c_failure --output-dir reports/shared_future_candidate_consequence_gate_c --cache-dir outputs/shared_future_candidate_consequence_gate_c/all
